import { Noto_Sans } from "next/font/google";

import "./globals.css";

// nextjs provides helper functions to load google fonts
// read more about fonts in nextjs here:
// https://nextjs.org/docs/app/building-your-application/optimizing/fonts#google-fonts
const noto = Noto_Sans({
  subsets: ["latin-ext"],
  // We can specify the font weights with numbers or names
  // 400 corresponds to "regular" and 700 corresponds to "bold".
  // This setting specifies that we only want to load the regular and bold weights
  // so we don't load the whole font family.
  weight: ["400", "700"],
  // we can reference the font in our css using the name we provided here
  variable: "--noto-sans",
});

export const metadata = {
  title: "TSMC Commuting",
  description: "Generated by create next app",
};

// The root layout is the outermost component that wraps all pages
// this prevents us from having to repeat the same layout code in every page
// it also prevents us from loading redundant javascript in every page
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={noto.className}>
        {/* use w-mobile to restrict width */}
        {/* use mx-auto to set the page in the middle */}
        <div className="container mx-auto h-mobile w-mobile bg-gray_light">
          {children}
        </div>
      </body>
    </html>
  );
}
